bookyourservices/views/home.py
from flask import Blueprint, render_template, g, request, flash, url_for, jsonify
from secrets import token_urlsafe

from flask.helpers import get_flashed_messages
from utils import *
from forms import *
from models import *
from views.modules.user import UserHandler
from views.modules.service import ServiceHandler
from views.modules.category import CategoryHandler
from views.modules.schedule import ScheduleHandler
from google_calendar.google_calendar import GoogleCalendarHandler


home = Blueprint('home', __name__)


############
# filters for displaying on templates


@home.app_template_filter('dt')
def _jinja2_filter_datetime(dt):

    return dt.strftime(DATETIME_FORMAT)


@home.app_template_filter('d')
def _jinja2_filter_date(d):

    return dt.strftime(DATE_FORMAT)


###########
# User Login methods


def login_required(func):
    """
    For the route need to login
    Check if the username in session
    Redirect to login page if not login yet
    """

    @wraps(func)
    def func_wrapper(*args, **kwargs):
        if login_username() is None:
            flash("Please login first!", FLASH_GROUP_DANGER)
            return redirect(f'{url_for("home.login")}?path={urllib.parse.quote_plus(request.path)}')

        return func(*args, **kwargs)

    return func_wrapper


##################
# Methods for before request


@home.before_request
def before_request_func():
    """Set current login user information"""

    g.global_values = {}

    if login_username():
        g.user = User.query.get(login_username())

        if g.user is not None:
            g.global_values["CURRENT_USERNAME"] = g.user.username

        if g.user is None:
            flash("Please login first!", FLASH_GROUP_DANGER)
            session.clear()
            return redirect(f'{url_for("home.login")}?path={urllib.parse.quote_plus(request.path)}')


@home.route('/')
def index():
    # Do some stuff

    service_form = ServiceSearchForm()
    service_form.categories.choices.extend(CategoryHandler.list_for_select())
    service_url = "/services"

    provider_form = BaseSearchForm()
    provider_url = "/providers"

    appointment_form = AppointmentForm(prefix="appointment")

    return render_template("home/index.html",
                           service_url=service_url,
                           service_form=service_form,
                           provider_url=provider_url,
                           provider_form=provider_form,
                           appointment_form=appointment_form)


@home.route('/services')
def services_list():
    """Service List"""

    service_form = ServiceSearchForm()
    service_form.categories.choices.extend(CategoryHandler.list_for_select())
    service_url = "/services"

    service_form.term.data = request.args.get("term", "")
    service_form.categories.data = request.args.get("categories", "0")

    appointment_form = AppointmentForm(prefix="appointment")

    return render_template("home/services.html",
                           service_url=service_url,
                           service_form=service_form,
                           appointment_form=appointment_form)


@home.route('/providers')
def providers_list():
    """Provider List"""

    provider_form = BaseSearchForm()
    provider_url = "/providers"

    provider_form.term.data = request.args.get("term", "")

    return render_template("home/providers.html",
                           provider_url=provider_url,
                           provider_form=provider_form)


@home.route('/providers/<string:username>')
def provider_detail(username):
    """Provider Detail"""

    user = User.query.get_or_404(username)

    g.global_values["PROVIDER_USERNAME"] = user.username

    return render_template("home/provider.html", account=user)


######
# For user accounts
#
@home.route('/login', methods=['POST', 'GET'])
def login():
    """login"""

    if (login_username()):
        # already login
        return redirect(url_for("home.dashboard"))

    form = UserLoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data

        user = User.authenticate(username, password)

        if user:
            login_username_set(username)

            path = request.args.get("path", "")

            if path == "":
                flash(f"Welcome Back, {user.full_name}!", FLASH_GROUP_SUCCESS)
                
                return redirect(url_for("home.dashboard"))
            else:
                flash(f"Welcome Back, {user.full_name}!", FLASH_GROUP_SUCCESS)
                
                return redirect(path)
        else:
            flash('Invalid username/password.', 'danger')

    return render_template('home/users/login.html', form=form)


@home.route('/register', methods=['POST', 'GET'])
def register():
    """New User Account"""

    form = UserForm()
    form_hide_value(form.password_edit, '')
    form_hide_value(form.first_name, '')
    form_hide_value(form.last_name, '')
    form_hide_value(form.description, '')
    form_hide_value(form.phone, '')
    form_hide_value(form.image, '')
    form_hide_value(form.is_active, True)

    if form.validate_on_submit():
        new_account = UserHandler.register(form)

        if new_account is not None:
            # login the new account and redirect to dashboard
            login_username_set(new_account.username)

            flash('Successfully Registered!', FLASH_GROUP_SUCCESS)
            return redirect(url_for("home.dashboard"))

    return render_template('home/users/register.html', form=form)


@home.route('/password_reset', methods=['POST', 'GET'])
def password_reset():
    """Reset Password"""

    token = request.args.get('token', None)

    if token is None:
        form = PasswordResetEmailForm()

        if form.validate_on_submit():
            if UserHandler.reset_password_email(form):

                flash('The reset email has been sent to you email address!',
                      FLASH_GROUP_SUCCESS)
                return redirect(url_for('home.login'))

            flash('Email is not found!', FLASH_GROUP_DANGER)

        return render_template('home/users/password_reset.html', form=form)

    user = User.query.filter(User.pwd_token == token,
                             User.is_active == True).first()

    if user is None:

        flash('Invalid Token, please try again!', FLASH_GROUP_DANGER)

        return redirect(url_for("home.password_reset"))

    # Set the new password
    form = PasswordResetForm()

    if form.validate_on_submit():

        account = UserHandler.reset_password(form=form, token=token)

        if account:
            login_username_set(account.username)

            flash('Successfully reset password!', FLASH_GROUP_SUCCESS)

            return redirect(url_for('home.dashboard'))

        flash('Error when updating password!', FLASH_GROUP_DANGER)

    return render_template('home/users/password_reset.html', form=form)


@home.route('/logout', methods=['POST'])
def logout():
    """logout"""

    session.clear()

    return redirect(url_for('home.login'))


@home.route('/users/dashboard')
@login_required
def dashboard():
    """Get user dashboard"""

    g.global_values["PROVIDER_USERNAME"] = g.user.username
    g.global_values["APPOINTMENT_LIST_URL"] = f'/api/appointments/{ g.user.username }?{"is_provider=1" if g.user.is_provider else ""}'
    g.global_values["APPOINTMENT_UPDATE_URL"] = '/api/appointments/0'
    g.global_values["APPOINTMENT_DELETE_URL"] = '/api/appointments/0'
    g.global_values["APPOINTMENT_PER_PAGE"] = '6'

    appointment_form = AppointmentForm(prefix="appointment")

    service_form = ServiceForm(prefix="service")
    service_form.category_ids.choices = CategoryHandler.list_for_select()

    return render_template("home/users/dashboard.html", account=g.user,
                           appointment_form=appointment_form,
                           service_form=service_form)


@home.route('/users/profile')
@login_required
def profile():
    """Get user dashboard"""

    return render_template("home/users/profile.html", account=g.user)


@home.route('/users/edit', methods=['POST', 'GET'])
@login_required
def user_edit():
    """Get user dashboard"""

    user = g.user

    form = UserForm(obj=user)

    form_hide_value(form.username, user.username)
    form_hide_value(form.password, user.password)
    form_hide_value(form.password_edit, '')
    form_hide_value(form.is_active, True)

    if form.validate_on_submit():
        user = UserHandler.update(user, form)

        if len(form.errors) == 0:
            # no error, redirect
            flash('Successfully Update Account!', FLASH_GROUP_SUCCESS)

            return redirect(url_for("home.profile"))

    return render_template('home/users/edit.html', form=form, account=user)


@home.route('/users/password', methods=['POST', 'GET'])
@login_required
def password_update():
    """Edit Password"""

    form = PasswordForm()

    if form.validate_on_submit():
        password = form.password.data

        account = User.update_password(login_username(), password)

        if account != False:
            flash('Successfully Updated Password!', FLASH_GROUP_SUCCESS)

            return redirect(url_for("home.password_update"))

    return render_template('home/users/password.html', form=form, account=g.user)


@home.route('/users/myservices')
@login_required
def my_services():
    """Get all my services"""

    if not g.user.is_provider:
        flash("Unauthorized visit!", FLASH_GROUP_DANGER)

        return redirect(url_for("home.dashboard"))

    form = ServiceForm(prefix="service")
    form.category_ids.choices = CategoryHandler.list_for_select()

    return render_template("home/services/list.html", form=form)


@home.route('/users/myschedules')
@login_required
def my_schedules():
    """Get all my schedules"""

    if not g.user.is_provider:
        flash("Unauthorized visit!", FLASH_GROUP_DANGER)

bookyourservices/templates/home/users/dashboard.html
{% extends 'home/base-login.html' %}

{% block subtitle %}
Dashboard
{% endblock %}

{% block top_links %}
<a class="btn btn-primary" href="{{ url_for('home.user_edit') }}" title="Edit"><i class="fas fa-user-edit"></i></a>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12 col-md-4">
        <img src="{{account.image_url}}" class="img-fluid" />
    </div>
    <div class="col-12 col-md-8 h4">
        <div class="row">
            <div class="col-4 text-primary">Name:</div>
            <div class="col-8 text-secondary">{{account.full_name}}</div>
            <div class="col-4 text-primary">Email:</div>
            <div class="col-8 text-secondary">{{account.email}}</div>
            <div class="col-4 text-primary">Phone:</div>
            <div class="col-8 text-secondary">{{account.phone}}</div>
            <div class="col-4 text-primary">Description:</div>
            <div class="col-8 text-secondary">{{account.description}}</div>
        </div>
    </div>
</div>

<div class="row p-2">
    <div class="col h2">
        Upcoming Appointments
    </div>
</div>

<div class="row container-fluid mx-auto">
    <div class="col-12 d-flex row py-2 bg-secondary text-white font-weight-bolder">
        <div class="col-2">{{"Customer" if g.user.is_provider else "Provider" }}</div>
        <div class="col">Service</div>
        <div class="col">Date</div>
        <div class="col">Time</div>
        <div class="col-1">Note</div>
        <div class="col-2">
            Actions
        </div>
    </div>
</div>
<div class="row container-fluid mx-auto" id="appointments-list">
</div>
{% if g.user.is_provider %}
<div class="row p-2">
    <div class="col h2">
        My Services
    </div>
</div>
<div class="row" id="services-list">
</div>
{% endif %}

{% with form = appointment_form %}
{% include "form-ajax-modal.html" %}
{% endwith %}
{% include ("home/items/myappointment-provider.html" if g.user.is_provider else "home/items/myappointment.html") %}

{% if g.user.is_provider %}

{% include "home/items/myservice.html" %}

{% with form = service_form %}
{% include "form-ajax-modal.html" %}
{% endwith %}

{% endif %}

{% endblock %}

{% block js %}
<script src="/static/js/home/users/myappointments.js" type="module"></script>

{% if g.user.is_provider %}
<script src="/static/js/home/users/myservices.js" type="module"></script>
{% endif %}

{% endblock %}

bookyourservices/templates/home/users/edit.html
{% extends 'home/base-login.html' %}

{% block subtitle %}
Username: <span class="text-success">{{account.username}}</span>
{% endblock %}

{% block top_links %}
<a class="btn btn-primary" href="{{ url_for('home.profile')}}"
        title="User Information"><i class="fas fa-user"></i></a>
{% endblock %}

{% block content %}
{% include 'form.html' %}
{% endblock %}

bookyourservices/templates/home/users/login.html
{% extends 'home/base.html' %}

{% block subtitle%}
<div class="container">User Login</div>
{% endblock%}

{% block top_links %}
{% endblock %}


{% block content %}
<div class="container">
    <form method="POST">

        {{ form.hidden_tag() }}

        {% for field in form
        if field.widget.input_type != 'hidden' %}
        <p>
            {{ field.label }}
            {{ field(class_="form-control") }}

            {% for error in field.errors %}
            <span class="form-text text-danger">{{ error }}</span>
            {% endfor %}
        </p>
        {% endfor %}

        <button class="btn btn-success" type="submit">Login</button> Forgot the password?<a
            href="{{ url_for('home.password_reset') }}">Click here</a> to reset.

    </form>
</div>
{% endblock %}

bookyourservices/templates/home/users/password.html
{% extends 'home/base-login.html' %}

{% block subtitle %}
Edit Password
{% endblock %}

{% block top_links %}
{% endblock %}

{% block content %}
{% include 'form.html' %}
{% endblock %}

bookyourservices/templates/home/users/password_reset.html
{% extends 'home/base.html' %}

{% block subtitle %}
Reset Password
{% endblock %}

{% block top_links %}
{% endblock %}

{% block content %}
<div class="container">
    {% include 'form.html' %}
</div>
{% endblock %}

bookyourservices/templates/home/users/profile.html
{% extends 'home/base-login.html' %}

{% block subtitle %}
My Profile
{% endblock %}

{% block top_links %}
<a class="btn btn-primary" href="{{ url_for('home.user_edit') }}" title="Edit"><i class="fas fa-user-edit"></i></a>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12 col-lg-4">
        <img src="{{account.image_url}}" class="img-fluid" />
    </div>
    <div class="col-12 col-lg-8 h4">
        <div class="row">
            <div class="col-4 text-primary">Name:</div>
            <div class="col-8 text-secondary">{{account.full_name}}</div>
            <div class="col-4 text-primary">Email:</div>
            <div class="col-8 text-secondary">{{account.email}}</div>
            <div class="col-4 text-primary">Phone:</div>
            <div class="col-8 text-secondary">{{account.phone}}</div>
            {% if g.user.is_provider %}
            <div class="col-4 text-primary">Calendar Gmail:</div>
            <div class="col-8 text-secondary">{{account.calendar_email}}</div>
            {% endif %}
            <div class="col-4 text-primary">Updated:</div>
            <div class="col-8 text-secondary">{{account.updated|dt}}</div>
            <div class="col-4 text-primary">Created:</div>
            <div class="col-8 text-secondary">{{account.created|dt}}</div>
            <div class="col-4 text-primary">Description:</div>
            <div class="col-8 text-secondary">{{account.description}}</div>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
{% endblock %}

bookyourservices/templates/home/users/register.html
{% extends 'home/base.html' %}

{% block subtitle%}
<div class="container">User Register</div>
{% endblock%}

{% block top_links %}
{% endblock %}


{% block content %}
<div class="container">
    {% include "form.html" %}
</div>

{% endblock %}